- README.md
- examples/token_delete.py
- src/hedera_sdk_python/crypto/private_key.py
- src/hedera_sdk_python/tokens/token_create_transaction.py
- src/hedera_sdk_python/tokens/token_delete_transaction.py
- test.py
- tests/conftest.py
- tests/test_token_create_transaction.py
- tests/test_token_delete_transaction.py
- uv.lock
Implemented the `TokenDeleteTransaction` class to handle token deletion on the Hedera network. 
- Added to example token deletion script in `examples/token_delete.py`
- Added `TokenDeleteTransaction` class in `src/tokens/token_delete_transaction.py`
- Created a unit test in `tests/test_token_delete_transaction.py`
- Added delete_token to the integration test `test.py' 
- Updated README with a usage example for token deletion
Unit tests passed locally.
Integration test added but not run. 
Mostly closes issue #2
> Token delete transaction

- README.md
- examples/token_create.py
- examples/token_freeze.py
- src/hiero_sdk_python/__init__.py
- src/hiero_sdk_python/crypto/private_key.py
- src/hiero_sdk_python/crypto/public_key.py
- src/hiero_sdk_python/tokens/token_create_transaction.py
- src/hiero_sdk_python/tokens/token_freeze_transaction.py
- test.py
- tests/test_token_create_transaction.py
- tests/test_token_freeze_transaction.py
> TokenFreezeTransaction

- examples/query_topic_message.py
- src/hiero_sdk_python/client/client.py
- src/hiero_sdk_python/client/network.py
- src/hiero_sdk_python/consensus/topic_message.py
- src/hiero_sdk_python/crypto/private_key.py
- src/hiero_sdk_python/crypto/public_key.py
- src/hiero_sdk_python/query/topic_message_query.py
- src/hiero_sdk_python/utils/crypto_utils.py
- src/hiero_sdk_python/utils/subscription_handle.py
Description:
This PR adds:
- ECDSA raw public key parsing is implemented (either 33-byte compressed or 65-byte uncompressed)
- added a close() method (and optionally enter/exit) to shut down the gRPC channels in the Client class.
- TopicMessageQuery enhancements: Cancellable subscription, completion handler, maxAttempts and maxBackoff for retry logic
Issue:
https://github.com/hiero-ledger/hiero-sdk-python/issues/43
> DID SDK improvements - Issue 43

- .github/workflows/test.yml
This PR is adding` installMirrorNode: true` to the test.yml pipeline to start a mirror node with every solo run
> Adding mirror node to actions

- .github/workflows/test.yml
> fix: test with the updated hiero-solo-action version

- src/hiero_sdk_python/crypto/private_key.py
> fix: use SEC1 ECPrivateKey instead of  PKCS#8

- .github/workflows/pr-checks.yml
Update step-security conventional-pr-title-action to use the new version 3.2.1
Fixes #78
> fix: Update pr-checks.yml

- examples/logging_example.py
- src/hiero_sdk_python/client/client.py
- src/hiero_sdk_python/executable.py
- src/hiero_sdk_python/logger/log_level.py
- src/hiero_sdk_python/logger/logger.py
- test.py
- tests/mock_server.py
- tests/test_logger.py
Add logging to the SDK by implementing custom logger.
* Add `LogLevel` enum with necessary levels 
* Create custom `Logger` class wrapping Python's logging module
* Add logger instance to Client class
* Add detailed logging throughout the executable flow
* Set logger to ERROR in integration tests and DISABLED in unit tests
**Checklist**
> feat: implement logger

- .github/workflows/test.yml
Fixes https://github.com/hiero-ledger/hiero-sdk-python/issues/91
**Checklist**
> fix: Bump solo-action to latest release

- examples/README.md
- examples/query_nft_info.py
- src/hiero_sdk_python/__init__.py
- src/hiero_sdk_python/query/token_nft_info_query.py
- src/hiero_sdk_python/tokens/token_nft_info.py
- tests/integration/token_nft_info_query_e2e_test.py
- tests/unit/conftest.py
- tests/unit/test_token_nft_info.py
- tests/unit/test_token_nft_info_query.py
Implement `TokenNftInfo` and `TokenNftInfoQuery` classes that allow retrieving detailed information about a specific NFT
* Implement `TokenNftInfo` class
* Add unit tests for `TokenNftInfo`
* Implement `TokenNftInfoQuery` class
* Add unit/integration tests for `TokenNftInfoQuery`
* Add `query_nft_info.py` example
* Update documentation in README and docstrings
* Update `__init__.py` file with  `TokenNftInfo` and `TokenNftInfoQuery` class definitions in `__all__` list
Fixes #14 and #24 
**Checklist**
> feat: add TokenNftInfoQuery

- examples/README.md
- examples/token_update_nfts.py
- src/hiero_sdk_python/__init__.py
- src/hiero_sdk_python/tokens/token_create_transaction.py
- src/hiero_sdk_python/tokens/token_update_nfts_transaction.py
- tests/integration/token_update_nfts_transaction_e2e_test.py
- tests/unit/test_token_create_transaction.py
- tests/unit/test_token_update_nfts_transaction.py
Implemented the `TokenUpdateNftsTransaction` class that updates metadata for specified NFTs in a collection.
* Add `metadata_key` attribute to `TokenCreateTransaction`
* Update `TokenCreateTransaction` unit tests with `metadata_key` and `wipe_key`
* Add `TokenUpdateNftsTransaction` class implementation
* Add  token update NFTs example
* Add unit tests for token update NFTs functionality
* Add integration tests
* Update `README.md` in examples folder
* Update `__init__.py` file with  `TokenUpdateNftsTransaction` class definition in `__all__` list
Fixes #18
In the PR for `TokenWipeTransaction` I forgot to add `wipe_key` to `TokenCreateTransaction` unit tests so I am doing it here together with `metadata_key`
**Checklist**
> feat: add  `TokenUpdateNftsTransaction`

- tests/unit/test_executable.py
- tests/unit/test_query.py
Add test coverage for `Query` class
* Add `test_query_retry_on_busy` in `test_executable.py` 
* Add `test_query.py` file that tests `Query` class
Fixes #117 
**Checklist**
> test: add unit tests for `Query`

- examples/README.md
- examples/token_burn_fungible.py
- examples/token_burn_nft.py
- src/hiero_sdk_python/__init__.py
- src/hiero_sdk_python/tokens/token_burn_transaction.py
- tests/integration/token_burn_transaction_e2e_test.py
- tests/unit/test_token_burn_transaction.py
Implemented the `TokenBurnTransaction` class that enables burning of tokens
* Add `TokenBurnTransaction` class implementation
* Add token burn examples for both fungible and non-fungible tokens
* Add integration/unit tests for `TokenBurnTransaction`
* Update `README.md` in examples folder with token burn documentation
* Update `__init__.py` file with `TokenBurnTransaction` class definition in `__all__` list
Fixes #129
**Checklist**
> feat: add `TokenBurnTransaction`

- examples/README.md
- examples/token_grant_kyc.py
- src/hiero_sdk_python/__init__.py
- src/hiero_sdk_python/tokens/token_create_transaction.py
- src/hiero_sdk_python/tokens/token_grant_kyc_transaction.py
- tests/integration/token_grant_kyc_transaction_e2e_test.py
- tests/unit/test_token_create_transaction.py
- tests/unit/test_token_grant_kyc_transaction.py
Implemented the `TokenGrantKycTransaction` class that enables granting KYC approval to accounts for specific tokens.
* Add `kyc_key` attribute to `TokenCreateTransaction`
* Update `TokenCreateTransaction` unit tests with `kyc_key`
* Add `TokenGrantKycTransaction` class implementation
* Add token grant KYC example
* Add integration/unit tests for `TokenGrantKycTransaction`
* Update `README.md` in examples folder
* Update `__init__.py` file with `TokenGrantKycTransaction` class definition in `__all__` list
Fixes #131 
**Checklist**
> feat: add `TokenGrantKycTransaction`

- .github/workflows/test.yml
> chore: Bump Solo-Action

- examples/README.md
- examples/token_update_fungible.py
- examples/token_update_key.py
- examples/token_update_keys.py
- examples/token_update_nft.py
- src/hiero_sdk_python/__init__.py
- src/hiero_sdk_python/tokens/token_info.py
- src/hiero_sdk_python/tokens/token_key_validation.py
- src/hiero_sdk_python/tokens/token_update_transaction.py
- tests/integration/token_update_transaction_e2e_test.py
- tests/unit/test_token_info.py
- tests/unit/test_token_update_transaction.py
Implemented the `TokenUpdateTransaction` class that updates properties of an existing token.
* Add metadata field in `TokenInfo` and update the unit tests
* Add `TokenKeyValidation` class for token key validation modes
* Add `TokenUpdateTransaction` class implementation with support for:
* Add `TokenUpdateParams` and `TokenUpdateKeys` data classes for structured parameter passing
* Add token update examples for both fungible and non-fungible tokens.
* Add token update example for key updating.
* Add integration/unit tests for `TokenUpdateTransaction`
* Update `README.md` in examples folder with token update documentation
* Update `__init__.py` file with `TokenUpdateTransaction` class definition in `__all__` list
Fixes #17  …
> feat: add `TokenUpdateTransaction`

- CHANGELOG.md
**Description:**
This release introduces comprehensive support for the Hedera Token Service, enabling a near full range of token-related operations. It also includes major foundational improvements to the SDK's core architecture, stability, and developer experience.
- Add enhanced support for Hedera Token Service (HTS) transactions and queries - eg support for NFT creation, transfer, and querying
- Add Executable abstraction, Duration class, and Node implementation
- Improve transaction safety with a require_frozen check
- Enhance Query objects with a get_cost() method
- Fix INVALID_NODE_ACCOUNT errors during node switching
- Clarify ed25519 key usage in examples
**Notes for reviewer:**
This is a large feature release (first one in 4 months), primarily focused on implementing the full set …
> chore: Release 0.1.3

- README.md
Aiming to close
https://github.com/hiero-ledger/hiero-sdk-python/issues/105
> fix: Hedera to Hiero solo

- src/hiero_sdk_python/account/account_balance.py
- src/hiero_sdk_python/account/account_create_transaction.py
- src/hiero_sdk_python/account/account_id.py
- src/hiero_sdk_python/address_book/node_address.py
- src/hiero_sdk_python/consensus/topic_info.py
- src/hiero_sdk_python/consensus/topic_message.py
Minor improvements given the current mypy settings
Solves
https://github.com/hiero-ledger/hiero-sdk-python/issues/159
> chore: Type improvements to account, address_book and consensus

- src/hiero_sdk_python/tokens/abstract_token_transfer_transaction.py
- src/hiero_sdk_python/tokens/token_airdrop_transaction.py
- src/hiero_sdk_python/tokens/token_nft_transfer.py
- src/hiero_sdk_python/tokens/token_transfer.py
- src/hiero_sdk_python/tokens/token_transfer_list.py
- src/hiero_sdk_python/transaction/transaction_record.py
- src/hiero_sdk_python/transaction/transfer_transaction.py
- tests/integration/token_airdrop_transaction_e2e_test.py
- tests/unit/test_token_airdrop_transaction.py
- tests/unit/test_token_nft_transfer.py
- tests/unit/test_token_transfer.py
- tests/unit/test_token_transfer_list.py
- tests/unit/test_transaction_record.py
Added `TokenAirdropTransaction` implementation
Fixes #136 
**Checklist**
> feat: Added TokenAirdropTransaction

- src/hiero_sdk_python/crypto/private_key.py
- src/hiero_sdk_python/crypto/public_key.py
**Changes Made**
Added missing module docstrings.
Reformatted long lines to comply with pylint limits.
Applied explicit raise ... from ... to improve error traceability (W0707).
Removed unnecessary elif after return (R1705).
Reordered imports for standard compliance (C0411 / C0415).
Fixes #188
Only pylint-related changes were made. No core logic was altered.
Some import-error and no-name-in-module issues persist due to local environment resolution and are not blocking execution or testing.
**Checklist**
> style: improve linting in crypto module

- examples/README.md
- examples/query_file_info.py
- src/hiero_sdk_python/__init__.py
- src/hiero_sdk_python/file/file_info.py
- src/hiero_sdk_python/file/file_info_query.py
- tests/integration/file_info_query_e2e_test.py
- tests/unit/test_file_info.py
- tests/unit/test_file_info_query.py
Implemented the FileInfoQuery class that retrieves information about an existing file.
* Add `FileInfo` for structured file information representation
* Add unit tests for `FileInfo` class
* Add `FileInfoQuery` class implementation
* Add unit tests for `FileInfoQuery` class
* Add integration tests for `FileInfoQuery`
* Update examples README with file info query documentation
* Add file info query example
* Add `FileInfoQuery` to `__init__.py` file in `__all__` list
Fixes #148
There is a known bug affecting the integration test. This will be resolved by fix #209 
**Checklist**
> feat: Add FileInfoQuery

- .env.example
- README.md
needed for further clarification after a user was struggling to add their env vars in Discord
Fixes #
**Checklist**
> chore: update env sample

- .github/workflows/pr-checks.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
Updates step security harden runner to v2.13.0
Fixes #227
> chore: Update step-security harden runner action to v2.13.0

- CHANGELOG.md
> chore: Release 1.4.0

- CHANGELOG.md
- README_upstream.md
Updated command to avoid dco signing other commits and just S signign to keep verified status
Fixes
https://github.com/hiero-ledger/hiero-sdk-python/issues/309
> chore: README fix rebase command

- .github/workflows/test.yml
- CHANGELOG.md
* Bump solo action to `v0.12`
Fixes #321
**Checklist**
> chore: bump solo version

- CHANGELOG.md
- generate_proto.py
Fixes https://github.com/hiero-ledger/hiero-sdk-python/issues/325
> fix: windows forward slash to backslash conversion in generate_proto.py

- CHANGELOG.md
- docs/sdk_developers/merge_conflicts.md
- docs/sdk_developers/rebasing.md
Updated README_upstream.md with detailed rebase instructions, also added changes suggested by @exploreriii in the previous PR (which had to be closed due to fork corruption).
Fixes #299 
**Checklist**
> docs: Update README_upstream.md with detailed rebase instructions

- CHANGELOG.md
- generate_proto.py
* Bump protobufs to v0.65
Fixes #391 
**Checklist**
> chore: bump protobufs version to `v0.66.0`

- .github/workflows/test.yml
- CHANGELOG.md
> chore: bump solo version to `0.14`

- CHANGELOG.md
- src/hiero_sdk_python/tokens/token_transfer_list.py
This PR fixes the Incompatible types in assignment (expression has type "TokenNftTransfer", variable has type "TokenTransfer") error in `token_transfer_list.py`.
Fixes #381
**Checklist**
> chore: Fix Type Error in the token_transfer_list.py
