hiero-ledger/hiero-sdk-python

README.md, examples/token_dissociate.py, src/hedera_sdk_python/tokens/token_dissociate_transaction.py, test.py, tests/test_token_dissociate_transaction.py
Token Dissociate created similar format.
- passes local tests
- passes solo network test
- test file includes minor changes to transfer and associate tokens for testing of token dissociate
=> TokenDissociateTransaction

.github/workflows/publish.yml, .github/workflows/test.yml, generate_proto.sh
This is the fix for the following issue:
https://github.com/hiero-ledger/hiero-sdk-python/issues/44
This PR is adding grpc into the publish pipeline. It also renames Hedera to Hiero - however, a subsequent PR will have to point to hiero-solo and hiero-protobufs after these repositories have been transferred. 
Successful pipeline run:
https://github.com/hiero-ledger/hiero-sdk-python/actions/runs/13136982482/job/36654596492
deployed package:
https://pypi.org/project/hiero-sdk-python/0.0.0.dev2/#files
=> Publish pipeline fix to address Issue 44

.github/workflows/pr-checks.yml
Prior: 
Error: Resource not accessible by integration
Consequence:
PR title checks were not checking
Approach:
Added status write permission
Added pull_request_target
I believe this is correct, but am new to this, links:
https://github.com/step-security/conventional-pr-title-action/tree/19fb561b33015fd2184055a05ce5a3bcf2ba3f54/
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target
=> fix: PRCheck write

src/hiero_sdk_python/crypto/public_key.py
fixes #62
Changed ECDSASecp256k1 to ECDSA_secp256k1 to conform with basic_types_pb2's declaration of the Key object initialization parameters.
=> fix: misnamed parameter

src/hiero_sdk_python/Duration.py, src/hiero_sdk_python/__init__.py, src/hiero_sdk_python/account/account_create_transaction.py, src/hiero_sdk_python/consensus/topic_create_transaction.py, src/hiero_sdk_python/consensus/topic_info.py, src/hiero_sdk_python/consensus/topic_update_transaction.py
Introduce a `Duration` class to represent time durations in seconds, a wrapper for the protobuf Duration class.
- Add `Duration` class with `seconds` attribute
- Implement validation to ensure `seconds` is an integer
- Add `to_proto` method to convert to `proto_Duration`
- Add `from_proto` class method to create `Duration` from `proto_Duration`
- Implement `__str__` and `__repr__` for string representations
- Implement `__eq__` for equality comparison
**Checklist**:
=> feat: Duration Class

src/hiero_sdk_python/transaction/transaction.py, tests/unit/conftest.py, tests/unit/test_account_create_transaction.py, tests/unit/test_token_associate_transaction.py, tests/unit/test_token_create_transaction.py, tests/unit/test_token_delete_transaction.py, tests/unit/test_token_dissociate_transaction.py, tests/unit/test_token_freeze_transaction.py, tests/unit/test_token_mint_transaction.py, tests/unit/test_token_unfreeze_transaction.py, tests/unit/test_token_wipe_transaction.py
Add transaction freezing requirement and reorganize test utilities
* Add `_require_frozen()` check in `Transaction` class
* Updated `sign()` and `to_proto()` to use `_require_frozen()`
* Move `utils_for_test.py` from `tests/integration` to `tests/` for better code organization
* Update unit tests to properly freeze transactions before execution
* Add `create_mock_client()` utility for testing transaction-related functionality
Fixes #95
- We need this changes so we can later fix `INVALID_NODE_ACCOUNT` during node switching. Currently, we can sign a transaction without freezing it first, but this is a problem because we need to build the transaction body bytes for each node in the network. By requiring freezing before signing, …
=> feat: add _require_frozen()

src/hiero_sdk_python/query/query.py, src/hiero_sdk_python/transaction/query_payment.py, src/hiero_sdk_python/transaction/transaction.py, tests/unit/test_account_create_transaction.py, tests/unit/test_executable.py, tests/unit/test_token_associate_transaction.py, tests/unit/test_token_create_transaction.py, tests/unit/test_token_delete_transaction.py, tests/unit/test_token_dissociate_transaction.py, tests/unit/test_token_freeze_transaction.py, tests/unit/test_token_mint_transaction.py, tests/unit/test_token_unfreeze_transaction.py, tests/unit/test_topic_create_transaction.py, tests/unit/test_topic_delete_transaction.py, tests/unit/test_topic_update_transaction.py
Improve `Transaction` to build transaction body bytes for all nodes to prevent invalid node account errors during node switching
* Change `transaction_body_bytes` from `bytes` to `dict[AccountId, bytes]` to store `bytes` for each node
* Change `signature_map` from `SignatureMap` to `dict[bytes, SignatureMap]` to store signatures for each transaction body
* Update `freeze_with` to build transaction body bytes for all nodes in the network
* Update `sign` function to sign all transaction body bytes and store signatures in the map
Fixes #94
- Previously, transactions were built only for the current node, which could cause "Invalid Node Account" errors when the transaction was sent to a different node
- Now, transactions are built …
=> fix: INVALID_NODE_ACCOUNT during node switching

examples/README.md, examples/token_reject.py, examples/token_reject_fungible_token.py, examples/token_reject_nft.py, src/hiero_sdk_python/__init__.py, src/hiero_sdk_python/tokens/token_reject_transaction.py, tests/integration/token_reject_transaction_e2e_test.py, tests/integration/utils_for_test.py, tests/unit/test_token_reject_transaction.py
Implement `TokenRejectTransaction` class that allows users to reject tokens.
* Implement `TokenRejectTransaction` class
* Add `opts` parameter to token creation functions in `utils_for_test.py` for flexible token creation
* Add unit/integration tests for `TokenRejectTransaction`
* Update documentation in README and docstrings
* Update `__init__.py` file with `TokenRejectTransaction` class definitions in `__all__` list
Fixes #20 
I added additional parameter `opts` in both `create_nft_token()` and `create_fungible_token()` in `utils_for_test.py` file. This makes the token creation more flexible by allowing custom modifications to the transaction before execution.  I added docstrings for both functions so the user can see how to …
=> feat: add `TokenRejectTransaction`

examples/query_payment.py, src/hiero_sdk_python/query/account_balance_query.py, src/hiero_sdk_python/query/query.py, src/hiero_sdk_python/query/transaction_get_receipt_query.py, tests/integration/query_e2e_test.py, tests/unit/test_account_balance_query.py, tests/unit/test_get_receipt_query.py, tests/unit/test_query.py, tests/unit/test_token_info_query.py, tests/unit/test_token_nft_info_query.py, tests/unit/test_topic_info_query.py
Implement the proper cost calculation and payment handling for queries, ensuring that paid queries are properly charged while free queries (like account balance) remain free.
* Add `_is_payment_required()` in `Query` base class to tell which queries require payment and which don't
* Add `get_cost()` functionality to calculate query execution costs
* Update `_make_request_header()` to return `COST_ANSWER` header if there isn't a user query payment set and payment is required for the query
* Remove hardcoded transaction fee for `TokenTransfer`
* Update unit tests
* Rename `_user_query_payment` to `payment_amount`
* Add integration tests
Fixes #
When a query requires payment but no payment amount is specified, the following flow …
=> feat: implement `get_cost()` functionality

examples/README.md, examples/token_revoke_kyc.py, src/hiero_sdk_python/__init__.py, src/hiero_sdk_python/tokens/token_revoke_kyc_transaction.py, tests/integration/token_revoke_kyc_transaction_e2e_test.py, tests/unit/test_token_revoke_kyc_transaction.py
Implemented the `TokenRevokeKycTransaction` class that enables revoking KYC approval from accounts for specific tokens.
* Add `TokenRevokeKycTransaction` class implementation
* Add token revoke KYC example
* Add integration/unit tests for `TokenRevokeKycTransaction`
* Update `README.md` in examples folder
* Update `__init__.py` file with `TokenRevokeKycTransaction` class definition in `__all__` list
Fixes #133
**Checklist**
=> feat: add `TokenRevokeKycTransaction`

examples/README.md, examples/query_record.py, src/hiero_sdk_python/__init__.py, src/hiero_sdk_python/account/account_id.py, src/hiero_sdk_python/query/transaction_get_receipt_query.py, src/hiero_sdk_python/query/transaction_record_query.py, src/hiero_sdk_python/tokens/token_nft_transfer.py, src/hiero_sdk_python/transaction/transaction_receipt.py, src/hiero_sdk_python/transaction/transaction_record.py, tests/integration/transaction_record_query_e2e_test.py, tests/unit/test_token_nft_transfer.py, tests/unit/test_transaction_record.py, tests/unit/test_transaction_record_query.py
Implemented the `TransactionRecordQuery` class that retrieves transaction records from the network.
* Add `TransactionRecord` class with transaction record data
* Add unit tests for `TransactionRecord` class
* Add `TransactionRecordQuery` class implementation for querying transaction records by transaction ID
* Add `_from_proto()` method to `TokenNftTransfer` class for easier protobuf deserialization
* Refactor `TransactionReceipt` to include `transaction_id` field so we can use it to execute `TransactionRecordQuery`
* Add transaction record query example
* Add integration/unit tests for `TransactionRecordQuery`
* Update `README.md` in examples with transaction record query documentation
* Update `__init__.py` file with `TransactionRecord` and `TransactionRecordQuery` class definitions …
=> feat: add `TransactionRecordQuery`

examples/README.md, examples/file_create.py, src/hiero_sdk_python/__init__.py, src/hiero_sdk_python/file/file_create_transaction.py, src/hiero_sdk_python/file/file_id.py, src/hiero_sdk_python/transaction/transaction_receipt.py, tests/integration/file_create_transaction_e2e_test.py, tests/unit/test_file_create_transaction.py, tests/unit/test_file_id.py
Implemented the `FileCreateTransaction` class that enables creating files on the network.
* Add `FileId` class for file identification
* Add unit tests for 'FileId'
* Add `FileCreateTransaction` class implementation
* Add file create example
* Add integration/unit tests for `FileCreateTransaction`
* Update `README.md` in examples folder
* Update `__init__.py` file with `FileCreateTransaction` class definition in `__all__` list
Fixes #145 
**Checklist**
=> feat: add `FileCreateTransaction`

Commit_Signing.md
Add a new Commit_Signing.md guide to clearly document how contributors can properly sign their commits using both GPG signatures and DCO sign-offs.
This guide is intended to help contributors pass the required merge checks and understand the steps needed to get a Verified badge on their commits.
Fixes #174 
The file is named Commit_Signing.md and is placed at the root.
Intended to be linked or referenced in contributing docs later.
Helps reduce friction for new contributors unfamiliar with GPG and DCO setup.
**Checklist**
=> docs: add commit signing guide

examples/README.md, examples/file_update.py, src/hiero_sdk_python/__init__.py, src/hiero_sdk_python/file/file_update_transaction.py, tests/integration/file_update_transaction_e2e_test.py, tests/unit/test_file_update_transaction.py
Implemented the `FileUpdateTransaction` class that allows updating file contents, metadata, and keys on the network.
* Add `FileUpdateTransaction` class implementation
* Add integration tests for `FileUpdateTransaction`
* Add unit tests for `FileUpdateTransaction` class
* Add file update example
* Add `FileUpdateTransaction` documentation in examples README
* Add `FileUpdateTransaction` to `__init__.py` file in `__all__` list
Fixes #149, #215
**Checklist**
=> feat: add `FileUpdateTransaction`

tests/unit/test_file_update_transaction.py
Fix pytest collection warning for `test_file_update_transaction_can_execute` by resolving `mock_hedera_servers` configuration issue.
* Fix broken mock server setup preventing test execution
* Resolve pytest collection warning where test was not recognized as callable function
* Extract hardcoded timestamp to constant
Fixes #224
Apologies for the oversight for the mock server configuration issue.
Also, I forgot to push the commit in the initial PR that extracts the hardcoded timestamp to a constant.
**Checklist**
=> fix: FileUpdateTransaction unit tests

CHANGELOG.md, examples/contract_delete.py, hiero/hedera_sdk_python/documentation/sdk_users/running_examples.md, src/hiero_sdk_python/__init__.py, src/hiero_sdk_python/contract/contract_delete_transaction.py, tests/integration/contract_delete_transaction_e2e_test.py, tests/unit/test_contract_delete_transaction.py
Implemented the `ContractDeleteTransaction` class that allows deleting smart contracts from the network.
* Add `ContractDeleteTransaction` class implementation
* Add integration tests for `ContractDeleteTransaction`
* Add unit tests for `ContractDeleteTransaction` class
* Add contract delete example
* Add `ContractDeleteTransaction` documentation in examples README
* Add `ContractDeleteTransaction` to `__init__.py` file in `__all__` list
* Update CHANGELOG with ContractDeleteTransaction addition
Fixes #200 
**Checklist**
=> feat: add `ContractDeleteTransaction`

CHANGELOG.md, README.md
Fixed readme as we currently have .sh
Solves https://github.com/hiero-ledger/hiero-sdk-python/issues/268
=> fix: docs generate proto py to sh

CHANGELOG.md, docs/sdk_users/running_examples.md, examples/account_delete.py, src/hiero_sdk_python/__init__.py, src/hiero_sdk_python/account/account_delete_transaction.py, tests/integration/account_delete_transaction_e2e_test.py, tests/unit/test_account_delete_transaction.py
Implemented the `AccountDeleteTransaction` class that allows deleting accounts from the network.
* Add `AccountDeleteTransaction` class implementation
* Add integration tests for `AccountDeleteTransaction`
* Add unit tests for `AccountDeleteTransaction` class
* Add account delete example
* Add `AccountDeleteTransaction` documentation in examples README
* Add `AccountDeleteTransaction` to `__init__.py` file in `__all__` list
* Update CHANGELOG with AccountDeleteTransaction addition
Fixes #255
**Checklist**
=> feat: add `AccountDeleteTransaction`

.pylintrc, CHANGELOG.md
Add Pylint configuration for consistent code quality standards
* Add .pylintrc configuration file
* fail-under: 10 → 8
* ignored-modules: empty → hiero_sdk_python.hapi.services.*_pb2,hiero_sdk_python.hapi.mirror.*_pb2
* jobs: 1 → 0
* max-args: 5 → 7
* max-branches: 12 → 15
* max-positional-arguments: 5 → 7
* generated-members: empty → .*_pb2\..*
* Removed bad-names section (foo, bar, baz, toto, tutu, tata)
* Removed bad-names-rgxs section
* Removed good-names-rgxs section
* Removed inlinevar-rgx section
* Removed method-rgx section
* Removed module-rgx section
* Removed name-group section
* Removed signature-mutators section
* Added trailing comma in redefined-outer-name disable rule
Fixes #271 
Maybe 8.0 failure threshold is …
=> feat: add pylintrc

CHANGELOG.md, docs/sdk_developers/rebasing.md
Fixes https://github.com/hiero-ledger/hiero-sdk-python/issues/289
=> chore: move README_upstream.md to docs as rebase.md

CHANGELOG.md, examples/file_create.py, src/hiero_sdk_python/tokens/token_relationship.py, tests/integration/file_create_transaction_e2e_test.py, tests/integration/token_airdrop_transaction_e2e_test.py, tests/integration/token_burn_transaction_e2e_test.py, tests/integration/token_update_transaction_e2e_test.py, tests/unit/test_file_create_transaction.py
Add camelCase → snake_case conversion in integration tests
* Convert all camelCase variables in integration tests to snake_case
* Update test function names and references accordingly
* Ensure all tests are consistent with Python naming conventions
Fixes #<insert-issue-number>
This change only touches test files for consistency and does not affect production code.
**Checklist**
=> fix: convert camelCase to snake_case in integration tests

CHANGELOG.md, examples/query_receipt.py, examples/query_topic_info.py, examples/query_topic_message.py, examples/topic_delete.py, examples/topic_message_submit.py, examples/topic_update.py, examples/transfer_hbar.py, examples/transfer_token.py
This PR  fixes errors in multiple example scripts occurring due to hardcoded values being used from `.env` file.
**Updated Files:**
- examples/transfer_token.py
- examples/transfer_hbar.py
- examples/topic_update.py
- examples/topic_message_submit.py
- examples/topic_delete.py
- examples/query_topic_message.py
- examples/query_topic_info.py
- examples/query_receipt.py
Fixes #336  and #338
**Checklist**
=> fix: Resolve value errors in example scripts cause due to optional values in `.env`

CHANGELOG.md, src/hiero_sdk_python/client/network.py, src/hiero_sdk_python/tokens/nft_id.py, src/hiero_sdk_python/tokens/token_id.py, src/hiero_sdk_python/utils/entity_id_helper.py, tests/unit/nft_id_test.py, tests/unit/test_entity_id_helper.py, tests/unit/test_token_id.py
This PR adds **checksum support** for Hiero entity ID.
**Changes introduces:**
- Added `entity_id_helper.py` which Implements checksum generation and validation logic
- Added unit tests for `entity_id_helper.py`
- Extended **TokenId**:
- Added `checksum` field
- Added `validate_checksum()` method
- Added `to_string_with_checksum` method for string representation with checksum
- Updated `nft_id.py`  to include checksum support
- Updated/added unit tests for `TokenId` and `NftId`
Closes #46 
- The checksum use in the tests are taken from the  implementation of  the [HIP-15](https://hips.hedera.com/hip/hip-15) specification.
- While this PR implements checksum support for `TokenId`, the same logic applies to other entity ID like …
=> feat: Checksum support for TokenId.from_string()
